name: "Ansible lint"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - roles/**
      - playbooks/**
  pull_request:
    branches:
      - main
    paths:
      - roles/**
      - playbooks/**

defaults:
  run:
    working-directory: provision

jobs:
  lint:
    name: "Ansible lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ansible
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install ansible
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ansible Galaxy install
        run: |
          ansible-galaxy install -r requirements.yml -p ${{ env.GALAXY_ROLES_PATH }}
          ansible-galaxy collection install -r requirements.yml -p ${{ env.GALAXY_COLLECTIONS_PATH }}
        env:
          GALAXY_ROLES_PATH: ".ansible_galaxy/roles"
          GALAXY_COLLECTIONS_PATH: ".ansible_galaxy/collections"

      - name: Run Linter
        run: ansible-lint .
